services:
  # Keycloak
  keycloak_postgres:
    image: postgres:16.2
    ports:
      - 5436:5432
    volumes:
      - keycloak_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 1234
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1234
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak_network

volumes:
  keycloak_volume:

networks:
  keycloak_network:
    driver: bridge