server:
  port: 8084
spring:
  application:
    name: task-service
  profiles:
    active: dev, config
  config:
    import: "optional:configserver:http://localhost:8888"
eureka:
  instance:
    prefer-ip-address: true
