spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeangHuy/SPRING_MINI_PROJECT_002_Group2_CLOUD_CONFIG.git
          force-pull: true
#          default-label: main
          default-label: khouch
#          default-label: chhunly

server:
  port: 8888
encrypt:
  key: 3a6a267c-c290-474d-82fb-6d29237820f0